language: python
python: "3.6"

sudo: false

install: true

before_install: 
  - pip install aiomysql
  - pip install codecov
  - pip install coverage

script: 
  - coverage run runtests.py

after_success:
  - codecov
