language: python
python: "3.7"

sudo: true

install: true

services:
  - mysql

before_install: 
  - mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE IF NOT EXISTS helo;' 
  - export HELO_DB_URL=mysql://root@127.0.0.1:3306/helo
  - pip install aiomysql
  - pip install pylint
  - pip install pytz
  - pip install pytest==5.1.3
  - pip install pytest-asyncio pytest-cov
  - pip install coveralls coverage

script: 
  - pylint helo --jobs=5 --reports=yes
  - ./runtests.sh

after_success:
  - coveralls
