language: python
python: "3.6"

sudo: false

install: true

before_install: pip install aiomysql

script: 
  - python3 -m unittest  tests/test_db.py
  - python3 -m unittest  tests/test_model.py
  - python3 -m unittest  tests/test_crud.py
