language: python
python: "3.7"

sudo: true

install: true

services:
  - mysql

before_install: 
  - mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE IF NOT EXISTS trod;' 
  - export TROD_DB_URL=mysql://root@127.0.0.1:3306/trod
  - pip install aiomysql
  - pip install pytz
  - pip install pytest pytest-asyncio pytest-cov
  - pip install coveralls coverage
  - pip install pylint

script: 
  - pylint trod --jobs=4 --reports=yes
  - ./runtests.sh

after_success:
  - coveralls
